### ISSUE TITLE
[功能请求]更好的容器支持

### ISSUE THREAD

**Issue by arenekosreal** [Tim-Paik/oicq-http2#10]
容器环境下难以进行键盘操作，因此手动输入密码或者触发扫码登录均是个很麻烦的事情，因此可能需要添加从配置或者环境变量中读取用户信息完成登录的功能

**Comment by Tim-Paik** [comment]
事实上这个功能早就想做了，但上游 oicq/icqq 给的登陆就只是一个函数，调用登陆函数之后手动输入密码和扫码是 icqq 负责的，我们没法干预，需要这个功能的话还是得上游支持

~~至少我上次读 oicq 的代码的时候还是这种情况~~

**Comment by Tim-Paik** [comment]
https://github.com/icqqjs/icqq/wiki/密码登录流程

这里可以看到，system.login.qrcode 是 icqq 负责将二维码打印到控制台的，而密码登录大概率也需要扫码，就被挡在这一步了。

不过我个人不建议使用容器，或者至少要挂载数据目录，否则太多设备登陆会被风控。
如果挂载数据目录的话实际上只需要在容器外登陆，拿到登陆信息之后把数据挂载到容器中，容器内是不需要手动登陆的，也不存在这个问题了。

**Comment by Stapxs** [comment]
最简单的方式就选择在自己电脑上登录完成，然后把整个 .oicq 配置文件挂载到容器中

![image](https://github.com/Tim-Paik/oicq-http2/assets/42486439/36661610-e4a7-4c16-8b83-692095fcfb3f)

其次也可以在启动容器时使用交互式方式启动便于在终端操作容器 emmm
下两种任意都可以使用：
- 挂载已有配置文件并交互式创建容器
`docker run -i -e ID=1234567890 -v /root/oicq-config:/root/.oicq --name oicq Tim-Paik/oicq2-http`
- 使用交互式启动已有的容器进行配置操作
`docker start -i oicq`

![image](https://github.com/Tim-Paik/oicq-http2/assets/42486439/cb17ff2a-504e-4b62-a7e5-7526c57f1901)

**Comment by arenekosreal** [comment]
好的，目前通过挂载数据卷的方式完成了容器中登录，感谢提供帮助
