### ISSUE TITLE
HTTPS & WSS support?

### ISSUE THREAD

**Issue by ParticleG** [Tim-Paik/oicq-http2#3]

**Comment by Tim-Paik** [comment]
暂时没有打算，因为本项目是 https://github.com/takayama-lily/oicq/tree/master/http-api 的 oicq2 的移植，基本是为内网设计的，可以说没怎么做安全方面的措施。

如果您是搭配 Stapxs-QQ-Lite-2.0 使用，建议使用 localhost 访问，而不是 github.io 的演示链接，保证全程内网才能保证安全。

如果您是想基于本项目二次开发，我建议您放弃 http-api，因为本项目也仅仅是用来快速兼容 oicq-http 的接口迁移到 oicq2，而 oicq2 的 api 设计本身对 http-api并不友好，建议使用其他的 rpc 框架进行前后端通信。

**Comment by ParticleG** [comment]
好，那还是自己搓一个吧）
