### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by bestruirui** [Tim-Paik/oicq-http2#8]
![image](https://github.com/Tim-Paik/oicq-http2/assets/89796393/e186fa53-2cf8-4871-8a53-3f4e29f49c01)

**Comment by Tim-Paik** [comment]
@Stapxs 看起来是上游问题 https://github.com/icqqjs/icqq/issues
这个分支是做了一些不兼容改动，上游没法直接合并

@Stapxs 其实 oicq 这个问题是修了的（x
https://github.com/takayama-lily/oicq/commit/7b58a0003285568d3c6cf4d9c72e87e4cc1c6390
https://github.com/takayama-lily/oicq/commit/56d18fd02271621803dfd1914ec9b28b8e54fba0

**Comment by Stapxs** [comment]
查看上游 issue，尝试使用协议 6（手机登录），如果不想被顶可以尝试使用协议 5（Mac 登录）
协议 5 登录会导致 uin 无效（无法获取群公告和文件），暂时不知道如何解决

> https://github.com/icqqjs/icqq/issues/30

**Comment by Stapxs** [comment]
> @Stapxs 看起来是上游问题 https://github.com/icqqjs/icqq/issues 这个分支是做了一些不兼容改动，上游没法直接合并
> 
> @Stapxs 其实 oicq 这个问题是修了的（x [takayama-lily/oicq@7b58a00](https://github.com/takayama-lily/oicq/commit/7b58a0003285568d3c6cf4d9c72e87e4cc1c6390) [takayama-lily/oicq@56d18fd](https://github.com/takayama-lily/oicq/commit/56d18fd02271621803dfd1914ec9b28b8e54fba0)

icqq 其实也修了但是有部分协议还是坏的 emmm

**Comment by bestruirui** [comment]
谢谢老哥
