### ISSUE TITLE
[错误] 文件夹不存在

### ISSUE THREAD

**Issue by Stapxs** [Tim-Paik/oicq-http2#9]
在初始化账号（使用密码登录）的情况下出现账号目录不存在的小问题

\> https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/60

**Comment by Tim-Paik** [comment]
这个文件夹是icqq需要的么？oicq应该不需要来着好像

**Comment by Stapxs** [comment]
> 这个文件夹是icqq需要的么？oicq应该不需要来着好像

在保存 password 的时候貌似直接保存文件缺失了文件夹
其实这个人 fork 过去修了

https://github.com/CeraceLee/oicq-http2/commit/3534881cae1ce0ee284d9a48ef7fab5141cc3aef

我只是想着影响不大就没管
之前其实也有遇到过类似的问题

https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/52#issuecomment-1518991244

既然有人提了就明天改改罢了（x
